# Generated by Django 5.2.18 on 2026-10-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shell', models.CharField(choices=[('git-bash', 'Git Bash'), ('powershell', 'PowerShell'), ('cmd', 'CMD'), ('zsh', 'zsh'), ('bash', 'bash')], max_length=20)),
                ('args', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('mode', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=5)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EditorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='JetBrains Mono', max_length=120)),
                ('font_size', models.PositiveSmallIntegerField(default=14)),
                ('font_weight', models.PositiveSmallIntegerField(default=400)),
                ('line_height', models.FloatField(default=1.5)),
                ('letter_spacing', models.FloatField(default=0)),
                ('ligatures', models.BooleanField(default=True)),
                ('word_wrap', models.BooleanField(default=False)),
                ('minimap', models.BooleanField(default=True)),
                ('breadcrumbs', models.BooleanField(default=True)),
                ('folding', models.BooleanField(default=True)),
                ('cursor_style', models.CharField(choices=[('line', 'Line'), ('block', 'Block'), ('underline', 'Underline')], default='line', max_length=10)),
                ('tab_size', models.PositiveSmallIntegerField(default=4)),
                ('insert_spaces', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=False)),
                ('theme_mode', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_settings', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.theme')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
