# Generated by Django 5.2.18 on 2026-10-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, max_length=80)),
                ('environment', models.CharField(choices=[('local', 'Local'), ('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='local', max_length=12)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('postgres', 'PostgreSQL')], default='mysql', max_length=10)),
                ('host', models.CharField(default='127.0.0.1', max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('username', models.CharField(max_length=120)),
                ('default_database', models.CharField(blank=True, max_length=120)),
                ('use_ssl', models.BooleanField(default=False)),
                ('ssh_enabled', models.BooleanField(default=False)),
                ('ssh_host', models.CharField(blank=True, max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_user', models.CharField(blank=True, max_length=120)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('keychain_ref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workspace')),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='database.databaseconnection')),
            ],
            options={
                'unique_together': {('connection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('kind', models.CharField(default='table', max_length=10)),
                ('row_estimate', models.BigIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='database.databaseschema')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('schema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('data_type', models.CharField(max_length=120)),
                ('nullable', models.BooleanField(default=True)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('default', models.CharField(blank=True, max_length=500, null=True)),
                ('extra', models.CharField(blank=True, max_length=120)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='database.databasetable')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
