# Generated by Django 5.2.18 on 2026-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='file_path',
            field=models.CharField(blank=True, help_text='SQLite database file (local hint)', max_length=500),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='engine',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('postgres', 'PostgreSQL'), ('sqlite', 'SQLite'), ('mssql', 'SQL Server')], default='mysql', max_length=12),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
