# Generated by Django 5.2.18 on 2026-10-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('remote_url', models.CharField(blank=True, max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='GitRemote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='origin', max_length=60)),
                ('url', models.CharField(max_length=500)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to='repositories.repository')),
            ],
            options={
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
