# Generated by Django 5.2.18 on 2026-10-06 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], max_length=10)),
                ('architecture', models.CharField(choices=[('x64', 'x64'), ('arm64', 'ARM64')], default='x64', max_length=5)),
                ('package_type', models.CharField(choices=[('exe', 'Installer (.exe)'), ('portable', 'Portable (.zip)'), ('dmg', 'Disk image (.dmg)'), ('appimage', 'AppImage'), ('deb', '.deb'), ('rpm', '.rpm')], max_length=10)),
                ('download_url', models.URLField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='bytes')),
                ('checksum', models.CharField(help_text='SHA-256 hex digest', max_length=64)),
                ('release_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_latest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at', 'platform', 'architecture'],
                'unique_together': {('version', 'platform', 'architecture', 'package_type')},
            },
        ),
    ]
